name: PR-$(System.PullRequest.PullRequestNumber)-$(Date:yyyyMMdd)$(Rev:.rr)
trigger:
  # Batch merge builds together while a merge build is running
  batch: true
  branches:
    include:
    - master
    - release*

pr:
  branches:
    include:
    - master
    - release*

resources:
  repositories:
  - repository: ComplianceRepo
    type: github
    endpoint: ComplianceGHRepo
    name: PowerShell/compliance

jobs:
- job: Compliance_Job
  pool:
    vmImage: windows-latest
  steps:
  - checkout: self
    clean: true
  - checkout: ComplianceRepo
    clean: true
  - template: ci-compliance.yml@ComplianceRepo



