trigger: none

parameters:
  - name: OfficialBuild
    type: boolean
    default: false

variables:
  - name: ob_outputDirectory
    value: '$(Build.ArtifactStagingDirectory)/ONEBRANCH_ARTIFACT'
  - name: LinuxContainerImage
    value: mcr.microsoft.com/onebranch/azurelinux/build:3.0
  - name: WindowsContainerImage
    value: onebranch.azurecr.io/windows/ltsc2022/vse2022:latest
  - name: templateFile
    value: ${{ iif(parameters.OfficialBuild, 'v2/OneBranch.Official.CrossPlat.yml@onebranchTemplates', 'v2/OneBranch.NonOfficial.CrossPlat.yml@onebranchTemplates')}}

resources:
  repositories:
  - repository: templates
    type: git
    name: OneBranch.Pipelines/GovernedTemplates
    ref: refs/heads/main

extends:
  template: v2/OneBranch.NonOfficial.CrossPlat.yml@templates  # The Official template may only be used by Production-classified pipelines

  parameters:
    featureFlags:
      WindowsHostVersion:
        Disk: Large
        Version: 2022
        Network: KS1
      incrementalSDLBinaryAnalysis: true
      needExceptionForUbuntuUsage: true
    cloudvault:
      enabled: false
    globalSdl:
      sbom:
        enabled: true
        packageName: Microsoft.PowerShell.Native
      codeql:
        compiled:
          enabled: true
      armory:
        enabled: false
      credscan:
        enabled: true
        scanFolder:  $(Build.SourcesDirectory)
      binskim:
        enabled: true
        exactToolVersion: 4.4.2
      apiscan:
        enabled: false
      tsaOptionsFile: .config\tsaoptions.json

    stages:
    - stage: WinBuildAndSign
      displayName: Windows Build and Sign
      jobs:
      - template: .pipelines/templates/build-sign-windows.yml@self
        parameters:
          ARCHITECTURE: 'x64'

      - template: .pipelines/templates/build-sign-windows.yml@self
        parameters:
          ARCHITECTURE: 'x86'

      - template: .pipelines/templates/build-sign-windows.yml@self
        parameters:
          ARCHITECTURE: 'x64_arm64'

    - stage: LinuxBuild
      displayName: Linux Build
      jobs:
      - template: .pipelines/templates/build-linux.yml@self
        parameters:
          ARCHITECTURE: 'linux-x64'
          Name: 'Build_Linux_x64'

      - template: .pipelines/templates/build-linux.yml@self
        parameters:
          ARCHITECTURE: 'linux-arm64'
          Name: 'Build_Linux_arm64'

      - template: .pipelines/templates/build-linux.yml@self
        parameters:
          ARCHITECTURE: 'linux-musl-x64'
          Name: 'Build_Linux_musl_x64'

      - template: .pipelines/templates/build-linux.yml@self
        parameters:
          ARCHITECTURE: 'osx'
          Name: 'Build_osx'

    - stage: LinuxBuildARM
      displayName: Linux ARM Build
      variables:
      - name: LinuxContainerImage
        value: onebranch.azurecr.io/linux/ubuntu-2204:latest

      jobs:
      - template: .pipelines/templates/build-linux.yml@self
        parameters:
          ARCHITECTURE: 'linux-arm'
          Name: 'Build_Linux_arm'
